name: Test

on: push

jobs:
  maven-unit-and-functional-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ hashFiles('**/pom.xml') }}
      - name: Launching tests with Maven
        run: mvn test -pl '!tests/mongodb-integration-tests'

  mongodb-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ hashFiles('**/pom.xml') }}
      - uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0
      - name: Launching tests with Maven
        run: |
          mvn install -Dmaven.test.skip=true
          mvn spring-boot:run -pl bootstrap -Dspring.profiles.active=mongo &
          mvn -pl tests/mongodb-integration-tests verify
